<a href="https://colab.research.google.com/github/RUMONMD89/Data-Science/blob/main/class%202%20Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.6 Rのパッケージ，Pythonのモジュール

### 3.6.1 Rのパッケージ

### 3.6.2 Pythonのモジュール

In [2]:
import math
import numpy as np
import pandas as pd

In [3]:
import numpy
numpy.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [32]:
import numpy as np
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
from numpy import array
array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [34]:
from numpy import *
array([1, 2, 3, 4])

array([1, 2, 3, 4])

## 3.3 コレクション

### 3.3.1 1次元データ

In [6]:
x = ['foo', 'bar', 'baz']

In [7]:
len(x)
#> 3

3

In [8]:
x[1]
#> 'bar'

'bar'

In [35]:
x[1] = 'BAR'
x # 結果の確認
#> ['foo', 'BAR', 'baz']

x[1] = 'bar' # 元に戻す．

In [38]:
x[-2]
#> 'bar' x[-1]=baz, x[-3]=foo

'bar'

In [40]:
x + ['qux']
#> ['foo', 'bar', 'baz', 'qux']

['foo', 'bar', 'baz', 'qux']

In [12]:
x = x + ['qux']
# あるいは
#x.append('qux')

x # 結果の確認
#> ['foo', 'bar', 'baz', 'qux']

['foo', 'bar', 'baz', 'qux']

#### 3.3.1.1 等間隔の数値からなる1次元データ(One-dimensional data consisting of evenly spaced numbers)

In [13]:
list(range(5))
#> [0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]

In [14]:
list(range(0, 11, 2))
#> [0, 2, 4, 6, 8, 10]

[0, 2, 4, 6, 8, 10]

In [15]:
import numpy as np
np.arange(0, 1.1, 0.5)
#> array([0. , 0.5, 1. ])

array([0. , 0.5, 1. ])

In [16]:
np.linspace(0, 100, 5)
#> array([ 0., 25., 50., 75., 100.])

array([  0.,  25.,  50.,  75., 100.])

In [17]:
[10] * 5
#> [10, 10, 10, 10, 10]

[10, 10, 10, 10, 10]

#### 3.3.1.2 ファクタ（Rのみ）

### 3.3.2 数値計算やデータ解析用の1次元データ(One-dimensional data for numerical calculations and data analysis)

In [18]:
import numpy as np
x = np.array([2, 3, 5, 7])

x + 10 # 加算
#> array([12, 13, 15, 17])

x * 10 # 乗算
#> array([20, 30, 50, 70])

array([20, 30, 50, 70])

In [41]:
x = [2, 3]
np.sin(x)
#> array([0.90929743, 0.14112001])

array([0.90929743, 0.14112001])

In [20]:
x = np.array([2,  3,   5,    7])
y = np.array([1, 10, 100, 1000])
x + y
#> array([   3,   13,  105, 1007])

x * y
#> array([   2,   30,  500, 7000])

array([   2,   30,  500, 7000])

In [21]:
np.dot(x, y)
# あるいは
x @ y

#> 7532

7532

In [22]:
x = np.array([True, False])
y = np.array([True, True])
x & y
#> array([ True, False])

array([ True, False])

#### 3.3.2.1 1次元データ同士の比較(Comparison between 1D data)

In [23]:
u = np.array([1, 2, 3])
v = np.array([1, 2, 3])
w = np.array([1, 2, 4])

all(u == v) # 全体の比較
#> True

all(u == w) # 全体の比較
#> False

u == v      # 要素ごとの比較(Element-wise comparison)
#> array([ True,  True,  True])

u == w      # 要素ごとの比較
#> array([ True,  True, False])

array([ True,  True, False])

In [24]:
(u == w).sum()  # 同じ要素の数(number of identical elements)
#> 2

(u == w).mean() # 同じ要素の割合
#> [1] 0.6666667

0.6666666666666666

### 3.3.3 複数種類のデータをひとまとめにする(Combine multiple types of data)

In [25]:
x = [1, "two"]

In [26]:
x[1]
#> 'two'

'two'

### 3.3.4 文字列と値のペアのコレクション(A collection of string-value pairs)

In [27]:
x = {'apple' : 'りんご',
     'orange': 'みかん'}

In [28]:
x['grape'] = 'ぶどう'

In [29]:
x['apple']
# あるいは
tmp = 'apple'
x[tmp]

#> 'りんご'

'りんご'

### 3.3.5 補足：コピーと参照(Side note: copy and reference)

In [30]:
x = ['foo', 'bar', 'baz']
y = x
y[1] = 'BAR' # yを更新する．
y
#> ['foo', 'BAR', 'baz']

x            # xも変わる．
#> ['foo', 'BAR', 'baz']

['foo', 'BAR', 'baz']

In [31]:
x = ['foo', 'bar', 'baz']
y = x.copy()             # 「y = x」とせずに，コピーする．
x == y, x is y
#> (True, False)         # xとyは，等価（内容は同じ）だが同一ではない．

y[1] = 'BAR'             # yを更新しても，
x
#> ['foo', 'bar', 'baz'] # xは変化しない．

['foo', 'bar', 'baz']